version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: unichat_db
    restart: always
    environment:
      POSTGRES_PASSWORD: gizlisifre
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
