-- UniChat classroom seed SQL
-- Bu dosya backend/tools/generate_classroom_seed_sql.py ile üretilir.
BEGIN;
DELETE FROM campus_spaces WHERE source_file = 'Derslikler.xlsx';
DELETE FROM classrooms WHERE source_file = 'Derslikler.xlsx';

INSERT INTO campus_buildings (building_name, normalized_building_name, aliases, normalized_aliases, source_file)
VALUES
    ('Mühendislik ve Doğa Bilimleri Fakültesi', 'muhendislik ve doga bilimleri fakultesi', '["Mühendislik ve Doğa Bilimleri Fakültesi", "Mühendislik Fakültesi", "Mühendislik Binası", "Mühendislik", "MDBF", "M.D.B.F.", "Mühendislik ve Doğa Bilimleri", "Mühendislik ve Doğa Bilimleri Fakültesi Binası"]'::jsonb, '["muhendislik ve doga bilimleri fakultesi", "muhendislik fakultesi", "muhendislik binasi", "muhendislik", "mdbf", "m d b f", "muhendislik ve doga bilimleri", "muhendislik ve doga bilimleri fakultesi binasi"]'::jsonb, 'Derslikler.xlsx')
ON CONFLICT (normalized_building_name) DO UPDATE SET
    building_name = EXCLUDED.building_name,
    aliases = EXCLUDED.aliases,
    normalized_aliases = EXCLUDED.normalized_aliases,
    source_file = EXCLUDED.source_file,
    updated_at = NOW();

INSERT INTO classrooms (building_name, floor_label, room_code, room_type, capacity, department_name, department_code, is_shared, normalized_room_code, normalized_building_name, search_text, source_file)
VALUES
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '101', 'Bilgisayar Laboratuvarı', 56, 'Ortak Kullanım', 'ORTAK', TRUE, '101', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 101 Bilgisayar Laboratuvarı Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 101', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '102', 'Standart', 120, 'Ortak Kullanım', 'ORTAK', TRUE, '102', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 102 Standart Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 102', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '105', 'Standart', 32, 'Bilgisayar Programcılığı', 'BP', FALSE, '105', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 105 Standart Bilgisayar Programcılığı BP muhendislik ve doga bilimleri fakultesi 105', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '109', 'Amfi', 104, 'Bilgisayar Programcılığı', 'BP', FALSE, '109', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 109 Amfi Bilgisayar Programcılığı BP muhendislik ve doga bilimleri fakultesi 109', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '106', 'Amfi', 104, 'Ortak Kullanım', 'ORTAK', TRUE, '106', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 106 Amfi Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 106', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', 'Zemin', 'z-103', 'Standart', 120, 'Ortak Kullanım', 'ORTAK', TRUE, 'z-103', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi Zemin z-103 Standart Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi z-103', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '113', 'Amfi', 104, 'Ortak Kullanım', 'ORTAK', TRUE, '113', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 113 Amfi Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 113', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '202', 'Standart', 120, 'Bilgisayar Mühendisliği', 'BM', FALSE, '202', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 202 Standart Bilgisayar Mühendisliği BM muhendislik ve doga bilimleri fakultesi 202', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', 'Zemin', 'z-114', 'Bilgisayar Laboratuvarı', 100, 'Bilgisayar Mühendisliği', 'BM', FALSE, 'z-114', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi Zemin z-114 Bilgisayar Laboratuvarı Bilgisayar Mühendisliği BM muhendislik ve doga bilimleri fakultesi z-114', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '110', 'Standart', 32, 'Bilgisayar Mühendisliği', 'BM', FALSE, '110', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 110 Standart Bilgisayar Mühendisliği BM muhendislik ve doga bilimleri fakultesi 110', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '206', 'Konferans Salonu', 120, 'Ortak Kullanım', 'ORTAK', TRUE, '206', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 206 Konferans Salonu Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 206', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '214', 'Amfi', 104, 'Ortak Kullanım', 'ORTAK', TRUE, '214', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 214 Amfi Ortak Kullanım ORTAK muhendislik ve doga bilimleri fakultesi 214', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '205', 'Standart', 32, 'Elektrik-Elektronik Mühendisliği', 'EEM', FALSE, '205', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 205 Standart Elektrik-Elektronik Mühendisliği EEM muhendislik ve doga bilimleri fakultesi 205', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', 'Zemin', 'z-112', 'Standart', 32, 'Elektrik-Elektronik Mühendisliği', 'EEM', FALSE, 'z-112', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi Zemin z-112 Standart Elektrik-Elektronik Mühendisliği EEM muhendislik ve doga bilimleri fakultesi z-112', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '209', 'Amfi', 104, 'Elektrik-Elektronik Mühendisliği', 'EEM', FALSE, '209', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 209 Amfi Elektrik-Elektronik Mühendisliği EEM muhendislik ve doga bilimleri fakultesi 209', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '211', 'Standart', 100, 'Endüstri Mühendisliği', 'EM', FALSE, '211', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 211 Standart Endüstri Mühendisliği EM muhendislik ve doga bilimleri fakultesi 211', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '2', '210', 'Standart', 100, 'Endüstri Mühendisliği', 'EM', FALSE, '210', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 2 210 Standart Endüstri Mühendisliği EM muhendislik ve doga bilimleri fakultesi 210', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '111', 'Standart', 100, 'Radyo, Televizyon ve Sinema', 'RTV', FALSE, '111', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 111 Standart Radyo, Televizyon ve Sinema RTV muhendislik ve doga bilimleri fakultesi 111', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '1', '114', 'Standart', 100, 'Radyo, Televizyon ve Sinema', 'RTV', FALSE, '114', 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 1 114 Standart Radyo, Televizyon ve Sinema RTV muhendislik ve doga bilimleri fakultesi 114', 'Derslikler.xlsx')
;

INSERT INTO campus_spaces (building_name, floor_label, space_name, space_type, department_name, department_code, aliases, normalized_space_name, normalized_aliases, normalized_building_name, search_text, source_file)
VALUES
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '4', 'Akademik personel odaları, Fakülte Sekreterliği', 'İdari Ofis', 'Akademik personel odaları, Fakülte Sekreterliği', NULL, '["Akademik personel odaları, Fakülte Sekreterliği", "Akademik personel odaları", "Fakülte Sekreterliği", "Sekreterlik", "Akademik Personel Odaları", "Akademik Personel"]'::jsonb, 'akademik personel odalari fakulte sekreterligi', '["akademik personel odalari fakulte sekreterligi", "akademik personel odalari", "fakulte sekreterligi", "sekreterlik", "akademik personel"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 4 Akademik personel odaları, Fakülte Sekreterliği İdari Ofis Akademik personel odaları, Fakülte Sekreterliği Akademik personel odaları, Fakülte Sekreterliği Akademik personel odaları Fakülte Sekreterliği Sekreterlik Akademik Personel Odaları Akademik Personel muhendislik ve doga bilimleri fakultesi akademik personel odalari fakulte sekreterligi akademik personel odalari fakulte sekreterligi akademik personel odalari fakulte sekreterligi sekreterlik akademik personel', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '3', 'Öğrenci İşleri', 'İdari Ofis', 'Öğrenci İşleri', NULL, '["Öğrenci İşleri", "Öğrenci İşleri Ofisi"]'::jsonb, 'ogrenci isleri', '["ogrenci isleri", "ogrenci isleri ofisi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 3 Öğrenci İşleri İdari Ofis Öğrenci İşleri Öğrenci İşleri Öğrenci İşleri Ofisi muhendislik ve doga bilimleri fakultesi ogrenci isleri ogrenci isleri ogrenci isleri ofisi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '4', 'Dekan, Dekan Yardımcısı', 'İdari Ofis', 'Dekan, Dekan Yardımcısı', NULL, '["Dekan, Dekan Yardımcısı", "Dekan", "Dekan Yardımcısı", "Dekanlık", "Dekan Yardımcılığı"]'::jsonb, 'dekan dekan yardimcisi', '["dekan dekan yardimcisi", "dekan", "dekan yardimcisi", "dekanlik", "dekan yardimciligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 4 Dekan, Dekan Yardımcısı İdari Ofis Dekan, Dekan Yardımcısı Dekan, Dekan Yardımcısı Dekan Dekan Yardımcısı Dekanlık Dekan Yardımcılığı muhendislik ve doga bilimleri fakultesi dekan dekan yardimcisi dekan dekan yardimcisi dekan dekan yardimcisi dekanlik dekan yardimciligi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '4', 'Bilgisayar Mühendisliği Bölüm Başkanlığı', 'İdari Ofis', 'Bilgisayar Mühendisliği Bölüm Başkanlığı', 'BM', '["Bilgisayar Mühendisliği Bölüm Başkanlığı", "Bölüm Başkanlığı", "BM", "BM Bölüm Başkanlığı"]'::jsonb, 'bilgisayar muhendisligi bolum baskanligi', '["bilgisayar muhendisligi bolum baskanligi", "bolum baskanligi", "bm", "bm bolum baskanligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 4 Bilgisayar Mühendisliği Bölüm Başkanlığı İdari Ofis Bilgisayar Mühendisliği Bölüm Başkanlığı BM Bilgisayar Mühendisliği Bölüm Başkanlığı Bölüm Başkanlığı BM BM Bölüm Başkanlığı muhendislik ve doga bilimleri fakultesi bilgisayar muhendisligi bolum baskanligi bilgisayar muhendisligi bolum baskanligi bolum baskanligi bm bm bolum baskanligi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '4', 'Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı', 'İdari Ofis', 'Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı', 'EEM', '["Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı", "Bölüm Başkanlığı", "EEM", "EEM Bölüm Başkanlığı"]'::jsonb, 'elektrik elektronik muhendisligi bolum baskanligi', '["elektrik elektronik muhendisligi bolum baskanligi", "bolum baskanligi", "eem", "eem bolum baskanligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 4 Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı İdari Ofis Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı EEM Elektrik-Elektronik Mühendisliği Bölüm Başkanlığı Bölüm Başkanlığı EEM EEM Bölüm Başkanlığı muhendislik ve doga bilimleri fakultesi elektrik elektronik muhendisligi bolum baskanligi elektrik elektronik muhendisligi bolum baskanligi bolum baskanligi eem eem bolum baskanligi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '4', 'Endüstri Mühendisliği Bölüm Başkanlığı', 'İdari Ofis', 'Endüstri Mühendisliği Bölüm Başkanlığı', NULL, '["Endüstri Mühendisliği Bölüm Başkanlığı", "Bölüm Başkanlığı"]'::jsonb, 'endustri muhendisligi bolum baskanligi', '["endustri muhendisligi bolum baskanligi", "bolum baskanligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 4 Endüstri Mühendisliği Bölüm Başkanlığı İdari Ofis Endüstri Mühendisliği Bölüm Başkanlığı Endüstri Mühendisliği Bölüm Başkanlığı Bölüm Başkanlığı muhendislik ve doga bilimleri fakultesi endustri muhendisligi bolum baskanligi endustri muhendisligi bolum baskanligi bolum baskanligi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '3', 'Radyo, Televizyon ve Sinema Bölüm Başkanlığı', 'İdari Ofis', 'Radyo, Televizyon ve Sinema Bölüm Başkanlığı', 'RTV', '["Radyo, Televizyon ve Sinema Bölüm Başkanlığı", "Bölüm Başkanlığı", "RTV", "RTV Bölüm Başkanlığı"]'::jsonb, 'radyo televizyon ve sinema bolum baskanligi', '["radyo televizyon ve sinema bolum baskanligi", "bolum baskanligi", "rtv", "rtv bolum baskanligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 3 Radyo, Televizyon ve Sinema Bölüm Başkanlığı İdari Ofis Radyo, Televizyon ve Sinema Bölüm Başkanlığı RTV Radyo, Televizyon ve Sinema Bölüm Başkanlığı Bölüm Başkanlığı RTV RTV Bölüm Başkanlığı muhendislik ve doga bilimleri fakultesi radyo televizyon ve sinema bolum baskanligi radyo televizyon ve sinema bolum baskanligi bolum baskanligi rtv rtv bolum baskanligi', 'Derslikler.xlsx'),
    ('Mühendislik ve Doğa Bilimleri Fakültesi', '3', 'Radyo, Televizyon ve Sinema (RTV) Bölüm Başkanlığı', 'İdari Ofis', 'Radyo, Televizyon ve Sinema Bölüm Başkanlığı', 'RTV', '["Radyo, Televizyon ve Sinema (RTV) Bölüm Başkanlığı", "Radyo, Televizyon ve Sinema Bölüm Başkanlığı", "Bölüm Başkanlığı", "RTV", "RTV Bölüm Başkanlığı"]'::jsonb, 'radyo televizyon ve sinema rtv bolum baskanligi', '["radyo televizyon ve sinema rtv bolum baskanligi", "radyo televizyon ve sinema bolum baskanligi", "bolum baskanligi", "rtv", "rtv bolum baskanligi"]'::jsonb, 'muhendislik ve doga bilimleri fakultesi', 'Mühendislik ve Doğa Bilimleri Fakültesi 3 Radyo, Televizyon ve Sinema (RTV) Bölüm Başkanlığı İdari Ofis Radyo, Televizyon ve Sinema Bölüm Başkanlığı RTV Radyo, Televizyon ve Sinema (RTV) Bölüm Başkanlığı Radyo, Televizyon ve Sinema Bölüm Başkanlığı Bölüm Başkanlığı RTV RTV Bölüm Başkanlığı muhendislik ve doga bilimleri fakultesi radyo televizyon ve sinema rtv bolum baskanligi radyo televizyon ve sinema rtv bolum baskanligi radyo televizyon ve sinema bolum baskanligi bolum baskanligi rtv rtv bolum baskanligi', 'Derslikler.xlsx')
;

COMMIT;
